//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluffy_Sweets
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fluffy_SweetsEntities : DbContext
    {
        public Fluffy_SweetsEntities()
            : base("name=Fluffy_SweetsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorizationSet> AuthorizationSet { get; set; }
        public virtual DbSet<ClientSet> ClientSet { get; set; }
        public virtual DbSet<ConfectionerSet> ConfectionerSet { get; set; }
        public virtual DbSet<RecordSet> RecordSet { get; set; }
        public virtual DbSet<SweetsSet> SweetsSet { get; set; }
    }
}
