//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluffy_Sweets
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordSet
    {
        public int Id { get; set; }
        public Nullable<int> IdConfectioner { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdSweets { get; set; }
        public Nullable<int> Prise { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        public virtual ConfectionerSet ConfectionerSet { get; set; }
        public virtual SweetsSet SweetsSet { get; set; }
    }
}
